### Register
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
  "name": "admin2",
  "email": "admin2@gmail.com",
  "password": "12345678"
}

### Login
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "12345678"
}

### Check Session
POST http://localhost:8000/api/v1/session
Content-Type: application/json

{
    "sessionId" : "cm6eyl39y0001irmeficfb7lz"
}